#指定运行环境
language: node_js
#指定nodejs版本，可以指定多个
node_js:
  - "8.10.0"
sudo: false
#运行的脚本命令
install:
  - yarn install
script:
  - yarn test
after_success:
  - cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master
